//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMPrac2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ORD_NUM { get; set; }
        public decimal ORD_AMOUNT { get; set; }
        public string ADVANCE_AMOUNT { get; set; }
        public System.DateTime ORD_DATE { get; set; }
        public string ORD_DESCRIPTION { get; set; }
        public int AGENT_CODE { get; set; }
        public int CUST_CODE { get; set; }
    
        public virtual AGENTS AGENTS { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
